### ISSUE TITLE
To be or not be (contribution)

### ISSUE THREAD

**Issue by mario-deluna** [php-collective/awesome-php#11]
#10 Got me thinking...

## About the rules

I think the main reason the maintenance of this awesome list was abandoned is the continuous discussion and difficulty in deciding what makes something "aweomse".

For example, I would love to add my own DI container library to the list, but with just 30 stars and barely any adoption outside of companies I'm in direct contact with, it misses the point. I believe it should **NOT** be a list of new packages that creators would like to promote, but rather reflect what's popular within the community. 

That's just my opinion, what do you think?

I think it might be a good point to review the rules and maybe strengthen them a bit. I would also gladly code some automated actions to enforce them.

Example rules for packages could include:
 - Every entry must be its own self-contained and documented package.
 - Must have at least x% of the GitHub stars of the lowest entry in its category. (or composer installations)
 - There should be a clear and concise README with examples of usage and installation instructions.
 - Package must support current versions of PHP.
 - Package must have had a commit / release within the last year / two.
 - The package must have been in existence for at least six months to a year to ensure it's not just a fleeting experiment.
 - A rule that limits the number of similar packages in a category can help to maintain the list's focus.

Again these are just examples..

## About the list

To perform as many checks as possible fully automatically, it might also make sense to introduce some sort of build process. By that, I mean having the package lists stored, for example, as JSON that is then built by a simple script into the README.md.

This would have some pros:
 - Packages could be automatically sorted by different terms.
 - We could automatically detect if a package becomes abandoned.
 - We could more easily enforce some of the rules.
 - We would not have to deal with formatting issues in PRs as packages are just structured data.

And, of course, some cons:
 - it may create a barrier to entry for contributors who are not familiar with the build process
 - If the build script has errors or becomes outdated, it could block updates
 - There's a risk of over-automation where useful human judgment and oversight might be bypassed, leading to a loss of qualitative curation.
 - ...

I would love to hear your thought on this, maybe we can have a bit of an open discussion about it.

**Comment by medilies** [comment]
I love the quantifiable rules (stars count, PHP version support, latest release, package age, and max element in category). And I support the idea of a structured list (YAML over JSON).

**Comment by alexkart** [comment]
I don't actually agree about star count as a library can be awesome but not so popular or maybe for some very unique use case. I like it more if a person who submits a library is actually describing why is this library better than other similar ones and this reasoning can be included in the list. Some of the common rules and recommendations are also listed in the `sindresorhus/awesome` repo https://github.com/sindresorhus/awesome/blob/main/create-list.md and they also have a linter for lists that checks various common issues.

**Comment by mario-deluna** [comment]
@alexkart Fair enough, do you want to adjust the "must" rules at all, or keep them as they are?

Would it be an option to create a [PR Template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) to structure add requests a bit more?

"Awesome Swift" does define one too: https://github.com/matteocrippa/awesome-swift/blob/master/.github/PULL_REQUEST_TEMPLATE, and their PRs are much easier to maintain as a result: https://github.com/matteocrippa/awesome-swift/pull/1817, at least I believe so 😅

**Comment by mario-deluna** [comment]
Sorry if I'm bombarding you with questions here. What about libraries like: https://github.com/namshi/notificator, which is currently on the list but hasn't been updated in 8 years and won't run under a currently maintained PHP version?

**Comment by alexkart** [comment]
> @alexkart Fair enough, do you want to adjust the "must" rules at all, or keep them as they are?
> 
> Would it be an option to create a [PR Template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) to structure add requests a bit more?
> 
> "Awesome Swift" does define one too: https://github.com/matteocrippa/awesome-swift/blob/master/.github/PULL_REQUEST_TEMPLATE, and their PRs are much easier to maintain as a result: [matteocrippa/awesome-swift#1817](https://github.com/matteocrippa/awesome-swift/pull/1817), at least I believe so 😅

Yes, I think PR Template is a good idea.

**Comment by alexkart** [comment]
> Sorry if I'm bombarding you with questions here. What about libraries like: https://github.com/namshi/notificator, which is currently on the list but hasn't been updated in 8 years and won't run under a currently maintained PHP version?

Definitely, if it is not maintained anymore we should remove it from the list.
