### ISSUE TITLE
Fully take over maintenance of ziadoz/awesome-php

### ISSUE THREAD

**Issue by dereuromark** [php-collective/awesome-php#2]
For this:
- [x] Fix up links that still point to https://github.com/ziadoz/awesome-php
- [ ] Add 5+ co-maintainers to help approve and merge PRs
- [ ] ?

No more bus factor from now on :)

**Comment by alexkart** [comment]
@dereuromark, hey, good idea, I can help with maintaining the project.

**Comment by mario-deluna** [comment]
Hey, @dereuromark, this is great! It's unfortunate how stale the awesome list has become. I would gladly help/contribute if tasks arise!

**Comment by dereuromark** [comment]
Seems like we are now maintaining on the original repo. So we can close here.
But first we need to port our progress back to the original repo as PR(s).

**Comment by dereuromark** [comment]
Please review/approve https://github.com/ziadoz/awesome-php/pull/1242
